apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stalwart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stalwart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stalwart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: stalwart
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: STALWART_ADMIN_PASSWORD
          value: "{{ .Values.config.adminPassword }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: smtp
          containerPort: 25
          protocol: TCP
        - name: imap
          containerPort: 143
          protocol: TCP
        - name: imaps
          containerPort: 993
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /opt/stalwart
        - name: appdata
          mountPath: /appdata
        - name: appcache
          mountPath: /appcache
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "stalwart.fullname" . }}-data
      - name: appdata
        hostPath:
          path: {{ .Values.userspace.appData }}/stalwart
          type: DirectoryOrCreate
      - name: appcache
        hostPath:
          path: {{ .Values.userspace.appCache }}/stalwart
          type: DirectoryOrCreate
