---
apiVersion: v1
kind: Service
metadata:
  name: getlood-authelia-svc
  namespace: auth-system
  labels:
    app: getlood-authelia
    component: authentication
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    cloud.google.com/backend-config: '{"default": "getlood-authelia-backend-config"}'
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: getlood-authelia
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: getlood-authelia-headless
  namespace: auth-system
  labels:
    app: getlood-authelia
    component: authentication
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: getlood-authelia
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091
